version: 1
formatters:
  simple:
    format: '%(asctime)s - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%dT%H:%M:%S'
  file:
    format: '%(asctime)s - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%dT%H:%M:%S'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout

  file:
    class: utils.handlers.logging_handlers.CustomFileHandler
    level: DEBUG
    formatter: file
    init_kwargs: 
      log_directory: 'logs'

loggers:
  root:
    level: INFO
    handlers: [console]

  download:
    level: DEBUG
    handlers: [console, file]
    propagate: no